Resources:
  MworxClientTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}-Mworx-Client
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: N
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  MworxConfigTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}-Mworx-Config
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  MworxSelfCareTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}-Mworx-Self-Care
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: N
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  MworxPaymentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}-Mworx-Payment
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
