service: mindworx
org: yourmindworx
app: mindworx-patient-portal

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  profile: mindworx-${self:provider.stage}
  timeout: 15
  # environment: ${file(env-${self:provider.stage}.yml)}
  # layers:
  #   - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-numpy:22
  #   - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-pandas:43
  # iam:
  #   role:
  #     statements:
  #       - Effect: 'Allow'
  #         Action:
  #           - secretsmanager:GetSecretValue
  #         Resource:
  #           - ${self:custom.dev.secret_arn_cognito}
  #           - ${self:custom.dev.secret_arn_mindbody}
  #           - ${self:custom.dev.secret_arn_drchrono}
  # - Effect: Allow
  #   Action:
  #     - dynamodb:DescribeTable
  #     - dynamodb:Query
  #     - dynamodb:Scan
  #     - dynamodb:GetItem
  #     - dynamodb:PutItem
  #     - dynamodb:UpdateItem
  #     - dynamodb:DeleteItem
  #   # Restrict our IAM role permissions to
  #   # the specific table for the stage

custom:
  customDomain:
    domainName: memberportal-${self:provider.stage}-api.yourmindworx.com
    basePath: 'mworx'
    stage: '${self:provider.stage}'
    createRoute53Record: true

  dev:
    cognito_arn : arn:aws:cognito-idp:us-east-1:472207946813:userpool/us-east-1_SroFJOV4n
    secret_arn_cognito: arn:aws:secretsmanager:us-east-1:472207946813:secret:COGNITO_DEV_SECRET-52ZbSv
    secret_arn_mindbody: arn:aws:secretsmanager:us-east-1:472207946813:secret:MINDBODY_DEV_SECRET-6sq4Qr
    secret_arn_drchrono: arn:aws:secretsmanager:us-east-1:472207946813:secret:DRCHRONO_DEV_SECRET-aEj61D
    secret_arn_vimeo: arn:aws:secretsmanager:us-east-1:472207946813:secret:VIMEO_DEV_SECRET-Onmint
    secret_arn_jotform: arn:aws:secretsmanager:us-east-1:472207946813:secret:JOTFORM_DEV_SECRET-1ArQC9
    secret_arn_twilio : arn:aws:secretsmanager:us-east-1:472207946813:secret:TWILIO_DEV_SECRET-AkduXK

  demo:
    cognito_arn : arn:aws:cognito-idp:us-east-1:472207946813:userpool/us-east-1_SroFJOV4n
    secret_arn_cognito: arn:aws:secretsmanager:us-east-1:472207946813:secret:COGNITO_DEV_SECRET-52ZbSv
    secret_arn_mindbody: arn:aws:secretsmanager:us-east-1:472207946813:secret:MINDBODY_DEV_SECRET-6sq4Qr
    secret_arn_drchrono: arn:aws:secretsmanager:us-east-1:472207946813:secret:DRCHRONO_DEV_SECRET-aEj61D
    secret_arn_vimeo: arn:aws:secretsmanager:us-east-1:472207946813:secret:VIMEO_DEV_SECRET-Onmint
    secret_arn_jotform: arn:aws:secretsmanager:us-east-1:472207946813:secret:JOTFORM_DEV_SECRET-1ArQC9
    secret_arn_twilio : arn:aws:secretsmanager:us-east-1:472207946813:secret:TWILIO_DEV_SECRET-AkduXK

  pythonRequirements:
    usePoetry: true
    useDownloadCache: true
    useStaticCache: false
    invalidateCaches: false
    slim: true

    noDeploy:
      - pytest

# resources: ${file(resources/dynamodb-table.yml)}

package:
  individually: false
  excludeDevDependencies: false
  patterns:
    - '!.vscode/**'
    - '!.pytest_cache/**'
    - '!.aws-sam/**'
    - '!node_modules/**'
    - '!infrastructure/**'
    - '!providers/**'
    - '!services/**'
    - '!tests/**'

plugins:
  - serverless-domain-manager
